### ISSUE TITLE
Crossbow of the Shattered Reflection with the Diffraction Barrel modifier creates an unreasonable number of projectiles, often crashing the game

### ISSUE THREAD

**Issue by StellaRoomy** [Sirplop/AetherworksRefracted#1]
The Diffraction Barrel's effect should only be allowed to activate on the initial firing, however it currently activates every time the projectile chains, leading to an exponential increase.

5-6 chains is enough to crash the game with Diffractive I

**Comment by Sirplop** [comment]
Now, whenever a projectile chains, if it hit something that was already hit, it will only produce 1 projectile instead of creating exponentially more.
Also fixed a crash where rays would infinitely chain between 2 entities while trying to reach a third.
Will be released in 1.0.4.
