### ISSUE TITLE
[BUG] Netherrack, Magma drop Stone Geodes instead of Netherrack, Magmatic geodes

### ISSUE THREAD

**Issue by UmbralSurvivor** [Sirplop/AetherworksRefracted#5]
Title.

Steps to reproduce:

- Get a pickaxe (preferably Boundless Sky aetherium pick) with a Tuning Cylinder attached
- Go to the nether
- Mine Netherrack and Magma
- Get Stone geodes instead of the appropriate type

**Comment by Sirplop** [comment]
The way it was checking biome tags was incorrect, and has been fixed.
